name: wallefy
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  animated_segmented_tab_control: ^1.0.1
  auto_size_text: ^3.0.0
  bloc_concurrency: ^0.2.1
  cached_network_image: ^3.2.3
  circular_seek_bar: ^1.1.0+2
  dartz: ^0.10.1
  dio: ^5.1.2
  equatable: ^2.0.5
  fl_chart: ^0.63.0
  floating_action_bubble: ^1.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.2
  get_it: ^7.6.0
  graphic: ^2.2.0
  group_button: ^5.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.6
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  lottie: ^2.3.2
  mask_text_input_formatter: ^2.4.0
  msix: ^3.15.0
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  syncfusion_flutter_datepicker: ^22.1.38

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/logo.png"

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
