name: wallefy
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Remote API
  http: ^0.13.6

  # Check connections
  internet_connection_checker: ^1.0.0+1

  # Local cache
  shared_preferences: ^2.1.1

  #cache images
  cached_network_image: ^3.2.3

  # Bloc / Cubit for state management
  flutter_bloc: ^8.1.3

  # dependency injector
  get_it: ^7.6.0
  # 6.Local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  intl: ^0.18.1
  # 16.Value equality
  equatable: ^2.0.5
  # 17.Functional programming thingies
  dartz: ^0.10.1
  # 13.Bloc cached clear helper
  bloc_concurrency: ^0.2.1
  dio: ^5.1.2
  flutter_svg: ^2.0.5
  flutter_screenutil: ^5.7.0
  mask_text_input_formatter: ^2.4.0
  auto_size_text: ^3.0.0
  group_button: ^5.3.0
  animated_segmented_tab_control: ^1.0.1
  fluttertoast: ^8.2.2
  lottie: ^2.3.2
  floating_action_bubble: ^1.1.4
  msix: ^3.15.0
  flutter_launcher_icons: ^0.13.1
  percent_indicator: ^4.2.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.2
  build_runner: ^2.1.8
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/lottie/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400

